### PR TITLE
Feature/hvg 783 add new claim payment types

### PR DESCRIPTION
**Pull request by Michael-Duivestein**
# Jira Issue: [HVG-783]

## What?
- Added deserializer that converts the JSON representation of Double or MonetaryAmount to Double.
- Added deserializer that converts the JSON representation of Double or MonetaryAmount to MonetaryAmount.
- Removed obsolete comment.

## Why?
This will help us transition from Double to MonetaryAmount more easily.

## Optional checklist
- [x] Codescouted
- [x] Unit tests written
- [x] Tested locally

[HVG-783]: https://hedvig.atlassian.net/browse/HVG-783

### CODE REVIEW

**Review by meletios — COMMENTED** [review]
Nice. Good move adding tests for that! ✌️ Small question, i checked that you are configuring the ObjectMapper on the tests, do we need to add something on the Jasckon config?

**Comment by Michael-Duivestein** [comment]
> Nice. Good move adding tests for that! v Small question, i checked that you are configuring the ObjectMapper on the tests, do we need to add something on the Jasckon config?

The ObjectMapper is automagically configured  by Spring. One of the modules it adds automagically is the MoneyModule.

**Review by vonElfvin — COMMENTED** [review]
This is really cool. Some thoughts though:
1. We could as well just change it to MonetaryAmount in both back-office and claims-service at the same time and deploy them. These endpoints are very rarely used so the risk is negligible.
2. Once we know this works we should remove this functionality and just straight up use MonetaryAmount in both services. If we at some point want to send a double this would make that very confusing.

**Comment by Michael-Duivestein** [comment]
> This is really cool. Some thoughts though:
> 
>     1. We could as well just change it to MonetaryAmount in both back-office and claims-service at the same time and deploy them. These endpoints are very rarely used so the risk is negligible.
> 
>     2. Once we know this works we should remove this functionality and just straight up use MonetaryAmount in both services. If we at some point want to send a double this would make that very confusing.

Once everything has been switched to MonetaryAmount, the intention is to remove these deserializers. adding them them so we have the ability to rollback back-office without needing to roll back claims-service. Perhaps I should have added this to the PR description.

**Comment by vonElfvin** [comment]
> > This is really cool. Some thoughts though:
> > ```
> > 1. We could as well just change it to MonetaryAmount in both back-office and claims-service at the same time and deploy them. These endpoints are very rarely used so the risk is negligible.
> > 
> > 2. Once we know this works we should remove this functionality and just straight up use MonetaryAmount in both services. If we at some point want to send a double this would make that very confusing.
> > ```
> 
> Once everything has been switched to MonetaryAmount, the intention is to remove these deserializers. adding them them so we have the ability to rollback back-office without needing to roll back claims-service. Perhaps I should have added this to the PR description.

Ok I understand, but since this is solely for the purpose of if we might want to revert either back-office or claims-service I'd say this makes it too complex given the small risk it has. IEX not being able to make claim payouts for 3 minutes due to us reverting some services is not a big thing. As long as we are aware of the risks then I'd say just go for it instead and change the dtos in both services at the same time. But if you want to be on the safe side I won't stop you :)

**Review by vonElfvin — APPROVED** [review]
👍

**Pull request merged**
